import type { Metadata } from 'next';
import './globals.css';
import { ThemeProvider } from './_components/shared/provider/ThemeProvider';
import { Toaster } from "@/components/ui/toaster"

export const metadata: Metadata = {
    title: 'CloudNest',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang='en'>
            <body
            >
                <ThemeProvider
                    attribute="class"
                    defaultTheme="system"
                    enableSystem
                    disableTransitionOnChange
                >
                    {children}
                    <Toaster />
                </ThemeProvider>
            </body>
        </html>
    );
}
